### ISSUE TITLE
AttributeDict doesn't convert nested items of list to AttributeDict

### ISSUE THREAD

**Issue by grundic** [prawn-cake/simple-models#17]
Here is an example:

```python
from simplemodels.models importAttributeDict

data = AttributeDict({'foo': [{'bar': 'baz'}]})
for item in data.foo:
    print(item.bar)

>>>Traceback (most recent call last):
>>>  File "/example.py", line 5, in <module>
>>>    print(item.bar)
>>>AttributeError: 'dict' object has no attribute 'bar'
```

Would switching to external implementation would be easier in this case? I would suggest [addict](https://github.com/mewwts/addict).
I don't like external dependencies, but from the other hand, implementing something from scratch could be quite error prone.

Also you have to wrap dictionary comprehensions with `AttributeDict` in 
[simplemodels/models.py:161](https://github.com/prawn-cake/simple-models/blob/master/simplemodels/models.py#L161) and [simplemodels/models.py:163](https://github.com/prawn-cake/simple-models/blob/master/simplemodels/models.py#L163)

**Comment by prawn-cake** [comment]
Thanks again for the report. Agree, it looks like a reasonable option. 
I'll check it or if you want, pull requests are most welcomed =)
It looks like a drop-in replacement, should be easy to implement

**Comment by grundic** [comment]
Well, first I would like to know your opinion on this topic.
Sure, I can do proposed replacement.

**Comment by prawn-cake** [comment]
I don't like external dependencies either, on the other hand no point to reinvent the wheel if the logic becomes more and more complex.
I checked the addict repo, it's active has good test coverage and seems to be stable, so we could rely on that if it doesn't have any side effects regarding the context of this project.

**Comment by grundic** [comment]
I've tried `addict` library, but it doesn't support descriptors, which are heavily used in the code of `simple-models`. There were some other problems, so I think it could be easier implement this in-place. Will give it a try :)

**Comment by prawn-cake** [comment]
No longer actual. Close it
