### ISSUE TITLE
Have you looked at 3rd party tools for more robust validation?

### ISSUE THREAD

**Issue by hairychris** [prawn-cake/simple-models#2]
How do you see this project in relation to tools such as:

https://github.com/nicolaiarocci/cerberus 

https://github.com/Julian/jsonschema

**Comment by prawn-cake** [comment]
Hi @hairychris, sure I did it, we follow different concepts.
Those projects implement schema validation features.

This project is about models and data consistency: my initial idea was to implement something like database models but without database dependency and aplicable for APIs, but saving data consistency, validation (sort of constaints), initialization features: describe a model and be sure that the data inside is following described constains across all of your workflow. 

Probably validation is not strong enough, I agree, but good enough anyway =)

Btw, which validation features you're talking about. Perhaps you have some use cases which are not covered.
