### ISSUE TITLE
ListField has several problems

### ISSUE THREAD

**Issue by grundic** [prawn-cake/simple-models#20]
1. You can't use string pointers to the models:

```python
class User(Base):
   friends = ListField(of='User')

>>> Exception: 'User' item type must be callable
```

2. ListField creates an instance of `list` for the given attribute. This makes modifier methods work not as expected:

```python
def test_append(self):
    class Post(Document):
        tags = ListField(of=str)

    post = Post()
    with self.assertRaises(ValidationError):
        post.tags.append(100500)  # not a string, should fail

>>> AssertionError: ValidationError not raised
```

Please, have a look at 236351df51965936e99ed6be126e1ee1dc9a5589 for more tests.

**Comment by prawn-cake** [comment]
Fixed in [v0.6.0](https://github.com/prawn-cake/simple-models/tree/0.6.0)
