### ISSUE TITLE
Add support of nested paths

### ISSUE THREAD

**Issue by grundic** [prawn-cake/simple-models#7]
Hello!
Great library, lightweight and not overwhelmed -- thanks a lot!

Can you add possibility to specify field disposition in case it's not at root level? Here is small example:

``` python
from jsonmodels import models, fields


class User(models.Base):
    name = fields.StringField()
    salary = fields.IntField()


data = {
    'name': 'John Smith',
    'data': {
        'salary': '100500'
    },

}

if __name__ == '__main__':
    user = User(**data)
    print(user.name)
    print(user.salary)

```

I would like to be able to specify in `User` model that the `salary` is nested under `data` path. And it should be possible to specify nested path. List of strings or usual uri should work fine:

``` python
class User(models.Base):
    name = fields.StringField()
    salary = fields.IntField(nested=['some', 'path'])
    # or
    salary = fields.IntField(nested='/some/path')
```

**Comment by grundic** [comment]
Wrong git repo :=O
Собирал ссылки на declarative frameworks и слегка промазал :)

**Comment by prawn-cake** [comment]
ok, а то смотрю что примеры не очень похожи =)
но фича весьма интересная, "get dict key by path" этакий

**Comment by grundic** [comment]
Да, фича хорошая. Возможно для твоей библиотеки тоже пригодится :)
https://www.haykranen.nl/2016/02/13/handling-complex-nested-dicts-in-python/ -- тут пример неплохой как раз по этой теме.
