### ISSUE TITLE
If data contains `self` it raises exception

### ISSUE THREAD

**Issue by grundic** [prawn-cake/simple-models#9]
``` python
from simplemodels.fields import CharField
from simplemodels.models import Document


class User(Document):
    name = CharField()
    self = CharField()


class Company(Document):
    name = CharField()


data = {
    'name': 'John Smith',
    'self': 'Handsome',
    'unused': 'foo/bar'
}

if __name__ == '__main__':
    print(User(**data))
    print(Company(**data))
```

This code would raise an exception `TypeError: __init__() got multiple values for keyword argument 'self'`. Should either filter it in **kwargs or replace dynamic arguments with dictionary options :-/
It would also raise en exception for classes that don't declare variable with `self` name.

**Comment by prawn-cake** [comment]
Good corner case, but this is fair for any python class allowing `**kwargs`, e.g the code

``` python
class A:
    def __init__(self, **kwargs):
        pass

A(self='hello')
```

Also will fail badly. And in general this is a bad practise to use reserved words for any purposes.
But giving the specific it might be a vulnerability, because the library suppose to be used to handle external data from/to API sources. Thanks.

UPD: you can't filter it in kwargs in the constructor, the way to handle it is to create models with static factory method with interface something like `MyModel.create(*args, **kwargs)`

**Comment by grundic** [comment]
Yep, exactly: the data comes from REST service, which is not under my control.
I understand the mechanics and what leads to this problem. One solution would be to filter all reserved words before passing them to the model and adding underscore for example to them. But in this case it would complicate the code and change model representation, so it would differ from original one.

Also in my case I use multiple inheritance with other class and it could have it's own parameters for constructor. If they will intersect with ones of the model's, it also would ruin the script.
Maybe it's not good design and I have to rethink, but now it could cause problems as well.

**Comment by grundic** [comment]
Oh, actually it works fine with multiple inheritance, as you are doing all fields work in metaclasses. I again mix it up with another library.

**Comment by prawn-cake** [comment]
New protected approach has been imlemented in [v0.5.0](https://github.com/prawn-cake/simple-models/tree/0.5.0)
Now recommended way to initialize a model is to use `Model.create({...})` factory method

**Comment by grundic** [comment]
Good work, but your implementation has one issue: if field would be named as a prefix, it could not be used. It's rare case, but I thought you should know :)

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from simplemodels.fields import CharField
from simplemodels.models import Document


class User(Document):
    name = CharField()
    self = CharField()
    User_ = CharField()


data = {
    'name': 'John Smith',
    'self': 'Handsome',
    'User_': 'doh',
    'unused': 'foo/bar'
}

if __name__ == '__main__':
    print(User.create(data))
>>> {'name': 'John Smith', 'User_': '', 'self': 'Handsome'}
```

Maybe just generate some random prefix for guarding reserved words?

**Comment by grundic** [comment]
I would suggest attach some random prefix in `DocumentMeta` class, so all Documents would have different prefixes. This should be more bulletproof solution.

**Comment by prawn-cake** [comment]
Good point.
But replacing only first match during converting protected keys back will be enough. For some reasons I expected that `str(...).replace(...)` does exactly this behavior. Fixed it in the [last dev](https://github.com/prawn-cake/simple-models/commit/f265404830d4ca83498e4ead9ef97386ab25aee5)

**Comment by grundic** [comment]
Sweet!
